### ISSUE TITLE
dependency unmet

### ISSUE THREAD

**Issue by jmoldon** [snakemake-workflows/cookiecutter-snakemake-workflow#5]
The default template requires pandas to work, but that dependency is not accounted for in the template:

In `workflow/rules/common.smk` pandas is used:

```python
import pandas as pd
```
so the template doesn't work as shipped.

```bash
$ snakemake -j 1
ModuleNotFoundError in line 2 of rna-seq/workflow/rules/common.smk:
No module named 'pandas'
  File "rna-seq/workflow/Snakefile", line 17, in <module>
  File "rna-seq/workflow/rules/common.smk", line 2, in <module>
```

**Comment by SilasK** [comment]
If you install (full) snakemake with conda pandas should also be installed.

**Comment by jmoldon** [comment]
OK, thanks. I was using `snakemake-minimal`, which doesn't include `pandas`.

I close the issue because your answer clarifies it. In any case, I would suggest to include the specific dependencies of a rule as a dedicated conda environment.
