### ISSUE TITLE
Where is the "Use This Template" button?

### ISSUE THREAD

**Issue by pbuendia** [snakemake-workflows/cookiecutter-snakemake-workflow#7]
Is cookiecutter-snakemake-workflow a Github template?

It says in the readme in Step 1
"Create a new github repository using this workflow as a template" : https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template

In that web page the instructions say to click on the "Use This Template" button but I don't see any. Do I have to request special access to it?

PB

**Comment by fritjoflammers** [comment]
I have the same issue. Would be cool if this could be addressed

**Comment by SilasK** [comment]
@mobilegenome Where did you read about the create template button?

If you want to use this repo follow this steps using cookie cutter: https://github.com/snakemake-workflows/docs#guidelines

See also : https://github.com/snakemake-workflows/docs/issues/2#issuecomment-963261075
